FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive \
	container=docker

# pre apt install locales and tzdata
RUN echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | debconf-set-selections && \
	echo "locales locales/default_environment_locale select en_US.UTF-8" | debconf-set-selections && \
	echo "tzdata	tzdata/Areas	select	America" | debconf-set-selections && \
	echo "tzdata	tzdata/Zones/America	select	Toronto" | debconf-set-selections && \
	echo "America/Toronto" > /etc/timezone && \
	ln -s /usr/share/zoneinfo/America/Toronto /etc/localtime

RUN DEBIAN_FRONTEND=noninteractive apt 2>/dev/null -qq update && \
	DEBIAN_FRONTEND=noninteractive apt 2>/dev/null -qq update && \
	DEBIAN_FRONTEND=noninteractive apt 2>/dev/null -yqq dist-upgrade && \
	DEBIAN_FRONTEND=noninteractive apt 2>/dev/null install -yqq \
	locales \
	toilet-fonts \
	toilet \
	caca-utils \
	wget \
	figlet
	
ENV LC_ALL="en_US.UTF-8"

ENTRYPOINT ["figlet", "Hello ${MY_NAME}"]
